---
name: Dillon Corrigan
position: "Biostatistician"
email: corrigan.dillon@gmail.com
phone: "(937) 620-2904"
github: dillonicus
docname: "Resume"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
class: "D:/CV/awesome-cv.cls"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE,
  cache = FALSE)

library(vitae)
library(dplyr)
library(glue)
library(scholar)
library(readr)
```

```{r get data, include = FALSE}

## Education
edu <- read_csv("D:/CV/data/education.csv")

## Jobs
jobs <- read_csv("D:/CV/data/jobs.csv") %>% 
  filter(category %in% "statistics")

## Publications
pubs <- scholar::get_publications("TlXo2mwAAAAJ") %>%
  dplyr::mutate(
    author = stringr::str_trim(as.character(author)),
    first_author = case_when(stringr::str_starts(author, "D Corrigan") ~ TRUE,
                             TRUE ~ FALSE)
    ) %>%
  dplyr::arrange(desc(year))

## Software

## Teaching

## Skills

skills <- read_csv("D:/CV/data/skills.csv") %>%
  group_by(category) %>%
  mutate(skill = paste(skill, collapse = ", ")) %>%
  ungroup %>%
  unique

```

# Experience

```{r}
detailed_entries(
  jobs,
  what = role,
  when = glue("{start_date} - {end_date}"),
  with = company,
  where = where,
  why = details
)
```

# Education
```{r}
detailed_entries(
  edu,
  when = glue("{start_date}--{end_date}"),
  what = degree,
  where = where,
  with = uni,
  why = details
)
```

# Publications

```{r}
detailed_entries(
  pubs,
  what = title,
  when = as.character(year),
  with = author,
  where = journal,
  .protect = TRUE
)
```
# Skills

```{r}
detailed_entries(
  skills %>% filter(category != "Other"),
  what = skill,
  with = category
)
```

